# Generated by Django 6.0.6 on 2026-06-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
